# Generated by Django 5.2.15 on 2026-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_status',
            field=models.CharField(choices=[('not_delivered', 'ডেলিভারি হয়নি'), ('delivered', 'ডেলিভারি সম্পন্ন')], default='not_delivered', max_length=20, verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'চলমান'), ('ready', 'প্রস্তুত'), ('completed', 'সম্পন্ন'), ('cancelled', 'বাতিল')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
    ]
