# Generated by Django 4.2.28 on 2026-06-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_order_delivery_date_alter_order_order_date'),
        ('transactions', '0005_customernote_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('product_description', models.TextField(blank=True, verbose_name='Product Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total Price')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
            ],
            options={
                'verbose_name': 'Customer Item (Deprecated)',
                'verbose_name_plural': 'Customer Items (Deprecated)',
            },
        ),
        migrations.CreateModel(
            name='CustomerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Submitted Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
            ],
            options={
                'verbose_name': 'Customer Submission (Deprecated)',
                'verbose_name_plural': 'Customer Submissions (Deprecated)',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='inventory_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.inventoryproduct', verbose_name='Inventory Product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Is Edited'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_versions', to='transactions.transaction', verbose_name='Original Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reverses_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by_transactions', to='transactions.transaction', verbose_name='Reversed Transaction'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', '-created_at'], name='transaction_custome_8b8f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_ed11cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_number'], name='transaction_transac_e5eca2_idx'),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='transactions.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.customersubmission', verbose_name='Submission'),
        ),
    ]
