# Generated by Django 4.2.28 on 2026-06-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_customeritem_customersubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernote',
            name='is_dismissed_from_dashboard',
            field=models.BooleanField(default=False, verbose_name='Dismissed from Dashboard'),
        ),
    ]
