# Generated by Django 5.2.15 on 2026-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_customer_deleted_at_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cash Paid'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Due Amount'),
        ),
    ]
