# Generated by Django 4.2.28 on 2026-06-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_cash_paid_transaction_due_amount'),
        ('transactions', '0028_transaction_related_purchase'),
    ]

    operations = [
    ]
