# Generated by Django 6.0.2 on 2026-02-04 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ক্রেতার নাম')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='মোবাইল নাম্বার')),
                ('product_name', models.CharField(max_length=200, verbose_name='পণ্যের নাম')),
                ('product_description', models.TextField(verbose_name='পণ্যের বিবরণ')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='মোট মূল্য')),
                ('cash_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='নগদ পরিশোধ')),
                ('due_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='বাকি টাকা')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='অর্ডার নেওয়ার তারিখ')),
                ('delivery_date', models.DateField(verbose_name='ডেলিভারির তারিখ')),
                ('status', models.CharField(choices=[('pending', 'চলমান'), ('completed', 'সম্পন্ন')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
            ],
            options={
                'verbose_name': 'অর্ডার',
                'verbose_name_plural': 'অর্ডারসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='পণ্যের নাম')),
                ('category', models.CharField(choices=[('door', 'দরজা'), ('window', 'জানালা'), ('grill', 'গ্রিল'), ('gate', 'গেট'), ('railing', 'রেলিং'), ('shed', 'শেড'), ('other', 'অন্যান্য')], max_length=50, verbose_name='ক্যাটাগরি')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='আনুমানিক দাম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'পণ্য',
                'verbose_name_plural': 'পণ্যসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='দোকানের নাম')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন নাম্বার')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='হোয়াটসঅ্যাপ নাম্বার')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
            ],
            options={
                'verbose_name': 'দোকানের তথ্য',
                'verbose_name_plural': 'দোকানের তথ্য',
            },
        ),
    ]
