# Generated by Django 6.0.2 on 2026-02-05 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='পণ্যের নাম')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('unit', models.CharField(choices=[('piece', 'পিস'), ('feet', 'ফুট'), ('meter', 'মিটার'), ('ton', 'টন'), ('kg', 'কেজি')], max_length=20, verbose_name='একক')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='প্রতি একক মূল্য')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='স্টক পরিমাণ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের তারিখ')),
            ],
            options={
                'verbose_name': 'ইনভেন্টরি পণ্য',
                'verbose_name_plural': 'ইনভেন্টরি পণ্যসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='ইনভয়েস নাম্বার')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ক্রেতার নাম')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='মোবাইল নাম্বার')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='বিক্রয়ের তারিখ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='সাবটোটাল')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ছাড় (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ছাড়ের পরিমাণ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='মোট টাকা')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='পরিশোধিত টাকা')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='বাকি টাকা')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
            ],
            options={
                'verbose_name': 'বিক্রয়',
                'verbose_name_plural': 'বিক্রয়সমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'চলমান'), ('ready', 'প্রস্তুত'), ('completed', 'সম্পন্ন')], default='pending', max_length=20, verbose_name='অবস্থা'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='পেমেন্টের তারিখ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='টাকার পরিমাণ')),
                ('payment_method', models.CharField(default='নগদ', max_length=50, verbose_name='পেমেন্ট পদ্ধতি')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.sale', verbose_name='বিক্রয়')),
            ],
            options={
                'verbose_name': 'পেমেন্ট',
                'verbose_name_plural': 'পেমেন্টসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক মূল্য')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='মোট মূল্য')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.inventoryproduct', verbose_name='পণ্য')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.sale', verbose_name='বিক্রয়')),
            ],
            options={
                'verbose_name': 'বিক্রয় আইটেম',
                'verbose_name_plural': 'বিক্রয় আইটেমসমূহ',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(default=django.utils.timezone.now, verbose_name='ফেরতের তারিখ')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ফেরত পরিমাণ')),
                ('reason', models.TextField(blank=True, verbose_name='কারণ')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ফেরত টাকা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='shop.saleitem', verbose_name='বিক্রয় আইটেম')),
            ],
            options={
                'verbose_name': 'মাল ফেরত',
                'verbose_name_plural': 'মাল ফেরতসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
