# Generated by Django 6.0.2 on 2026-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_inventoryproduct_sale_alter_order_status_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ক্রেতার নাম'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='মোবাইল নাম্বার'),
        ),
    ]
