# Generated by Django 6.0.2 on 2026-02-05 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_sale_customer_name_alter_sale_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='sale_item',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='ইনভয়েস নাম্বার')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ক্রেতার নাম')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='মোবাইল নাম্বার')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক মূল্য')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='সাবটোটাল')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ছাড়')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='মোট টাকা')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='বিক্রয়ের তারিখ')),
                ('is_latest', models.BooleanField(default=True, verbose_name='সর্বশেষ ভার্সন')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_versions', to='shop.invoice', verbose_name='মূল ইনভয়েস')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.inventoryproduct', verbose_name='পণ্য')),
            ],
            options={
                'verbose_name': 'ইনভয়েস',
                'verbose_name_plural': 'ইনভয়েসসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
