# Generated by Django 6.0.2 on 2026-02-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_return_sale_item_remove_saleitem_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ছাড় (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='বাকি টাকা'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='পরিশোধিত টাকা'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='ছাড়ের টাকা'),
        ),
    ]
