# Generated by Django 6.0.2 on 2026-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_invoice_discount_percentage_invoice_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('not_delivered', 'ডেলিভারি হয়নি'), ('delivered', 'ডেলিভারি সম্পন্ন')], default='not_delivered', max_length=20, verbose_name='ডেলিভারি অবস্থা'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'চলমান'), ('ready', 'প্রস্তুত'), ('completed', 'সম্পন্ন')], default='pending', max_length=20, verbose_name='প্রোডাক্ট অবস্থা'),
        ),
    ]
