# Generated by Django 4.2.28 on 2026-02-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_delivery_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/', verbose_name='ছবি'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='ছবি'),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='লোগো'),
        ),
    ]
