# Generated by Django 4.2.28 on 2026-02-09 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিশোধিত পরিমাণ')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='পেমেন্ট তারিখ')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.order', verbose_name='অর্ডার')),
            ],
            options={
                'verbose_name': 'অর্ডার পেমেন্ট',
                'verbose_name_plural': 'অর্ডার পেমেন্টসমূহ',
                'ordering': ['-payment_date'],
            },
        ),
    ]
