# Generated by Django 4.2.28 on 2026-02-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_payment_migrated',
            field=models.BooleanField(default=False, verbose_name='প্রাথমিক পেমেন্ট OrderPayment-এ স্থানান্তরিত'),
        ),
    ]
