# Generated by Django 4.2.28 on 2026-03-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_initial_payment_migrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.inventoryproduct', verbose_name='পণ্য'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='সাবটোটাল'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='মোট টাকা'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='একক মূল্য'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক মূল্য')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='সাবটোটাল')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.invoice', verbose_name='ইনভয়েস')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.inventoryproduct', verbose_name='পণ্য')),
            ],
            options={
                'verbose_name': 'ইনভয়েস আইটেম',
                'verbose_name_plural': 'ইনভয়েস আইটেমসমূহ',
            },
        ),
    ]
