# Generated by Django 4.2.28 on 2026-03-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_invoice_product_alter_invoice_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='ছাড়ের টাকা'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ছাড় (%)'),
        ),
    ]
