# Generated by Django 4.2.28 on 2026-03-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_invoiceitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='মোট মূল্য'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='পণ্যের নাম')),
                ('product_description', models.TextField(blank=True, verbose_name='পণ্যের বিবরণ')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক মূল্য')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='মোট মূল্য')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='অর্ডার')),
            ],
            options={
                'verbose_name': 'অর্ডার আইটেম',
                'verbose_name_plural': 'অর্ডার আইটেমসমূহ',
            },
        ),
    ]
