# Generated by Django 4.2.28 on 2026-03-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_order_product_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryproduct',
            unique_together={('name', 'unit')},
        ),
    ]
