# Generated by Django 4.2.28 on 2026-04-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_unique_constraint_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'স্টক যোগ'), ('remove', 'স্টক কমানো'), ('sale', 'বিক্রয়'), ('adjustment', 'সমন্বয়')], max_length=20, verbose_name='অপারেশন')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পূর্ববর্তী স্টক')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='নতুন স্টক')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তারিখ ও সময়')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='shop.inventoryproduct', verbose_name='পণ্য')),
            ],
            options={
                'verbose_name': 'স্টক হিস্ট্রি',
                'verbose_name_plural': 'স্টক হিস্ট্রিসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
