# Generated by Django 4.2.28 on 2026-04-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ক্রেতার নাম')),
                ('mobile_number', models.CharField(max_length=20, unique=True, verbose_name='মোবাইল নাম্বার')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
            ],
            options={
                'verbose_name': 'ক্রেতা',
                'verbose_name_plural': 'ক্রেতাসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ক্রেতার নাম'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='মোবাইল নাম্বার'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customer', verbose_name='ক্রেতা'),
        ),
    ]
