# Generated by Django 4.2.28 on 2026-04-29 14:32

from django.db import migrations


def migrate_orders_to_customers(apps, schema_editor):
    """Migrate existing orders to customers"""
    Order = apps.get_model('shop', 'Order')
    Customer = apps.get_model('shop', 'Customer')
    
    # Get all orders that have customer info but no customer linked
    orders_to_migrate = Order.objects.filter(customer__isnull=True).exclude(
        customer_name__isnull=True
    ).exclude(
        customer_name=''
    ).exclude(
        mobile_number__isnull=True
    ).exclude(
        mobile_number=''
    )
    
    # Track created customers to avoid duplicates
    customer_map = {}
    
    for order in orders_to_migrate:
        # Normalize mobile number (remove spaces, dashes)
        clean_mobile = ''.join(c for c in order.mobile_number if c.isdigit())
        
        # Check if we already created a customer for this mobile
        if clean_mobile in customer_map:
            customer = customer_map[clean_mobile]
        else:
            # Check if customer already exists in database
            try:
                customer = Customer.objects.get(mobile_number=clean_mobile)
            except Customer.DoesNotExist:
                # Create new customer
                customer = Customer.objects.create(
                    name=order.customer_name,
                    mobile_number=clean_mobile,
                    address=''
                )
            customer_map[clean_mobile] = customer
        
        # Link order to customer
        order.customer = customer
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_customer_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_orders_to_customers, migrations.RunPython.noop),
    ]
