# Generated by Django 4.2.28 on 2026-05-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_discount_amount_order_discount_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পুরাতন মূল্য')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='নতুন মূল্য')),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='পরিবর্তনের শতাংশ')),
                ('is_bulk', models.BooleanField(default=False, verbose_name='বাল্ক আপডেট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তারিখ ও সময়')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='shop.inventoryproduct', verbose_name='পণ্য')),
            ],
            options={
                'verbose_name': 'মূল্য ইতিহাস',
                'verbose_name_plural': 'মূল্য ইতিহাসসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
