# Generated by Django 4.2.28 on 2026-05-22 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='ডেলিভারির তারিখ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='অর্ডার নেওয়ার তারিখ'),
        ),
    ]
