# Generated by Django 3.2.12 on 2026-05-31 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='জমা ব্যালেন্স'),
        ),
        migrations.CreateModel(
            name='CustomerDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('transaction_type', models.CharField(choices=[('deposit', 'জমা'), ('deduct', 'কাটা')], default='deposit', max_length=20, verbose_name='লেনদেনের ধরন')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='shop.customer', verbose_name='ক্রেতা')),
            ],
            options={
                'verbose_name': 'গ্রাহক জমা',
                'verbose_name_plural': 'গ্রাহক জমাসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
