# Generated by Django 5.2.15 on 2026-06-08 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20260531_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ক্রেতার নাম')),
                ('mobile_number', models.CharField(max_length=20, unique=True, verbose_name='মোবাইল নাম্বার')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
            ],
            options={
                'verbose_name': 'টেস্ট কাস্টমার',
                'verbose_name_plural': 'টেস্ট কাস্টমারসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCustomerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='জমার পরিমাণ')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='জমার তারিখ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='shop.testcustomer', verbose_name='ক্রেতা')),
            ],
            options={
                'verbose_name': 'টেস্ট কাস্টমার জমা',
                'verbose_name_plural': 'টেস্ট কাস্টমার জমাসমূহ',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='TestCustomerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='পণ্যের নাম')),
                ('product_description', models.TextField(blank=True, verbose_name='পণ্যের বিবরণ')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক মূল্য')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='মোট মূল্য')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='যুক্ত তারিখ')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.testcustomersubmission', verbose_name='জমা')),
            ],
            options={
                'verbose_name': 'টেস্ট কাস্টম আইটেম',
                'verbose_name_plural': 'টেস্ট কাস্টম আইটেমসমূহ',
            },
        ),
    ]
