# Generated by Django 5.2.15 on 2026-06-08 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_testcustomer_testcustomersubmission_testcustomeritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcustomeritem',
            options={'verbose_name': 'টেস্ট কাস্টম আইটেম (পুরাতন)', 'verbose_name_plural': 'টেস্ট কাস্টম আইটেমসমূহ (পুরাতন)'},
        ),
        migrations.AlterModelOptions(
            name='testcustomersubmission',
            options={'ordering': ['-submission_date'], 'verbose_name': 'টেস্ট কাস্টমার জমা (পুরাতন)', 'verbose_name_plural': 'টেস্ট কাস্টমার জমাসমূহ (পুরাতন)'},
        ),
        migrations.AddField(
            model_name='testcustomer',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='বর্তমান ব্যালেন্স'),
        ),
        migrations.CreateModel(
            name='TestCustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='লেনদেন নাম্বার')),
                ('transaction_type', models.CharField(choices=[('submission', 'জমা'), ('purchase', 'ক্রয়'), ('withdrawal', 'উত্তোলন'), ('adjustment', 'সমন্বয়'), ('reversal', 'বাতিল')], max_length=20, verbose_name='লেনদেনের ধরন')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='পূর্ববর্তী ব্যালেন্স')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='নতুন ব্যালেন্স')),
                ('item_name', models.CharField(blank=True, max_length=200, verbose_name='পণ্যের নাম')),
                ('item_description', models.TextField(blank=True, verbose_name='পণ্যের বিবরণ')),
                ('item_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='পরিমাণ')),
                ('item_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='একক মূল্য')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('completed', 'সম্পন্ন'), ('cancelled', 'বাতিলকৃত')], default='completed', max_length=20, verbose_name='অবস্থা')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='বাতিল হয়েছে')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের সময়')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='তৈরিকারী')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_transactions', to='shop.testcustomer', verbose_name='ক্রেতা')),
                ('inventory_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.inventoryproduct', verbose_name='ইনভেন্টরি পণ্য')),
                ('reverses_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by_transactions', to='shop.testcustomertransaction', verbose_name='বাতিলকৃত লেনদেন')),
            ],
            options={
                'verbose_name': 'টেস্ট লেনদেন',
                'verbose_name_plural': 'টেস্ট লেনদেনসমূহ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='shop_testcu_custome_480bed_idx'), models.Index(fields=['transaction_type', 'status'], name='shop_testcu_transac_68dea8_idx'), models.Index(fields=['transaction_number'], name='shop_testcu_transac_6257be_idx')],
            },
        ),
    ]
