# Generated by Django 5.2.15 on 2026-06-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_add_test_transaction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcustomertransaction',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='গ্রস অ্যামাউন্ট'),
        ),
        migrations.AddField(
            model_name='testcustomertransaction',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='সম্পাদিত হয়েছে'),
        ),
        migrations.AddField(
            model_name='testcustomertransaction',
            name='item_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='পণ্যের ছাড়ের টাকা'),
        ),
        migrations.AddField(
            model_name='testcustomertransaction',
            name='item_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='পণ্যের ছাড় (%)'),
        ),
        migrations.AddField(
            model_name='testcustomertransaction',
            name='original_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_versions', to='shop.testcustomertransaction', verbose_name='মূল লেনদেন'),
        ),
        migrations.AddField(
            model_name='testcustomertransaction',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='মোট ছাড়ের টাকা'),
        ),
        migrations.AddField(
            model_name='testcustomertransaction',
            name='total_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='মোট ছাড় (%)'),
        ),
        migrations.CreateModel(
            name='TestCustomerTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='পণ্যের নাম')),
                ('product_description', models.TextField(blank=True, verbose_name='পণ্যের বিবরণ')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক মূল্য')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ছাড় (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='ছাড়ের টাকা')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='গ্রস অ্যামাউন্ট')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='নেট অ্যামাউন্ট')),
                ('inventory_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.inventoryproduct', verbose_name='ইনভেন্টরি পণ্য')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.testcustomertransaction', verbose_name='লেনদেন')),
            ],
            options={
                'verbose_name': 'টেস্ট লেনদেনের আইটেম',
                'verbose_name_plural': 'টেস্ট লেনদেনের আইটেমসমূহ',
            },
        ),
    ]
