# Generated by Django 5.2.15 on 2026-06-08 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_testcustomertransaction_gross_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'তৈরি হয়েছে'), ('edited', 'সম্পাদিত হয়েছে'), ('reversed', 'বাতিল হয়েছে'), ('deleted', 'মুছে ফেলা হয়েছে')], max_length=20, verbose_name='অ্যাকশন')),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='পুরাতন পরিমাণ')),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='নতুন পরিমাণ')),
                ('old_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='পুরাতন ব্যালেন্স')),
                ('new_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='নতুন ব্যালেন্স')),
                ('notes', models.TextField(blank=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তারিখ ও সময়')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='কর্মকর্তা')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shop.testcustomertransaction', verbose_name='লেনদেন')),
            ],
            options={
                'verbose_name': 'টেস্ট লেনদেনের ইতিহাস',
                'verbose_name_plural': 'টেস্ট লেনদেনের ইতিহাসসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
