# Generated by Django 5.2.15 on 2026-06-08 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_testtransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcustomertransaction',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='ডেলিভারির তারিখ'),
        ),
        migrations.AddField(
            model_name='testcustomertransaction',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='অর্ডারের তারিখ'),
        ),
    ]
