# Generated by Django 4.2.28 on 2026-06-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_order_delivery_date_alter_order_order_date'),
        ('shop', '0025_testcustomertransaction_delivery_date_and_more'),
    ]

    operations = [
    ]
