# Generated by Django 4.2.28 on 2026-06-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_order_delivery_date_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcustomertransaction',
            name='cash_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='নগদ পরিশোধ'),
        ),
    ]
